sudo: false
language: rust

matrix:
  include:
    - rust; 1.15.0
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - cargo test
  - |
      if [ "${TRAVIS_RUST_VERSION}" = nightly ]; then
          cargo clean
          cargo test --manifest-path compiletest/Cargo.toml
      fi
