sudo: false
language: rust

matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - |
      case "$TRAVIS_RUST_VERSION" in
          1.15.0)
              cargo build
              ;;
          nightly)
              cargo test
              cargo clean
              cargo test --manifest-path compiletest/Cargo.toml
              ;;
          *)
              cargo test
              ;;
      esac
