[package]
name = "ref-cast"
version = "0.2.7" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Safely cast &T to &U where the struct U contains a single field of type T."
repository = "https://github.com/dtolnay/ref-cast"
documentation = "https://docs.rs/ref-cast"
readme = "README.md"

[dependencies]
ref-cast-impl = { version = "=0.2.7", path = "derive" }

[dev-dependencies]
rustversion = "1.0"
trybuild = "1.0"

[workspace]
members = ["derive"]

[badges]
travis-ci = { repository = "dtolnay/ref-cast" }
