[package]
name = "ref-cast-impl"
version = "0.2.1" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Derive implementation for ref_cast::RefCast."
repository = "https://github.com/dtolnay/ref-cast"
documentation = "https://docs.rs/ref-cast-impl"

[lib]
name = "ref_cast_impl"
proc-macro = true

[dependencies]
syn = "0.13"
quote = "0.5"
