[package]
name = "ref-cast-impl"
version = "0.2.5"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Derive implementation for ref_cast::RefCast."
repository = "https://github.com/dtolnay/ref-cast"
documentation = "https://docs.rs/ref-cast-impl"

[lib]
name = "ref_cast_impl"
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"

[badges]
travis-ci = { repository = "dtolnay/ref-cast" }
