[package]
name = "ref-cast-impl"
version = "1.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Derive implementation for ref_cast::RefCast."
repository = "https://github.com/dtolnay/ref-cast"
documentation = "https://docs.rs/ref-cast-impl"

[lib]
name = "ref_cast_impl"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[badges]
travis-ci = { repository = "dtolnay/ref-cast" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
